name: customer
services:
  customer:
    image: customer:latest
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=customer
      - OTEL_EXPORTER_OTLP_INSECURE=true
    depends_on:
      otel-collector:
        condition: service_started
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.141.0
    hostname: otel-collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "13133:13133" # health_check extension
      - "55679:55679" # zpages extension
      - "1777:1777" # pprof extension
